name: "Deploy to AWS S3"
description: "Deploy static website via AWS S3"
inputs:
  bucket-name:
    description: "The S3 bucket name"
    required: true
  bucket-region:
    description: "The S3 bucket region"
    required: false
    default: "ap-southeast-1"
  dist-folder:
    description: "The folder containing deployable files"
    required: true
outputs:
  website-url:
    description: "The URL deployed website"

runs:
  using: "node16"
  main: "main.js"
